[project]
name = "h1b-data-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "altair>=5.4.1",
    "fastexcel>=0.12.0",
    "polars>=1.9.0",
]
